# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "centos-6.6-64-puppet"
  config.vm.box_url = "https://s3.amazonaws.com/platform-repo.ec2.nytimes.com/dev/shared/virtualbox/centos-6.6-x86_64-puppet-3.7.4-1.box"
  config.vm.network :private_network, ip: "192.168.33.13"
  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 1
  end
  
  config.vm.provision "shell", inline: <<-SHELL

sudo yum install -y emacs-nox
sudo chkconfig iptables off 123456
sudo /etc/init.d/iptables stop
cd /vagrant
if [ ! -f /vagrant/consul ]; then
  unzip /vagrant/consul.zip
  fi
sudo echo "NETWORKING=yes
HOSTNAME=consul4" > /etc/sysconfig/network
  hostname consul4

  sudo rpm --import /vagrant/RPM-GPG-KEY.dag.txt
  sudo rpm -q gpg-pubkey-$(echo $(gpg --throw-keyids < /vagrant/RPM-GPG-KEY.dag.txt) | cut --characters=11-18 | tr '[A-Z]' '[a-z]')

sudo rpm -i /vagrant/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm || true
sudo rpm -i /vagrant/epel-release-6-8.noarch.rpm || true
sudo rpm -i /vagrant/remi-release-6.rpm || true
sudo yum install -y nginx

  SHELL
end
